Problem 1
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
Output: [ True False False True False]

In [10]:
import numpy as np
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))


#print(array1)
array2_input = input("Enter elements for array2 separated by spaces: ")
array2 = np.array(list(map(int, array2_input.split())))

result=np.isin(array1,array2)
print(result)

[ True False False  True False]


Problem 2
Write a NumPy program to get the unique elements of an array
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]


In [13]:
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
input_array = []
for i in range(rows):
    row_input = input(f"Enter elements for row {i + 1} separated by spaces: ")
    row = list(map(int, row_input.split()))
    input_array.append(row)
array3 = np.array(input_array)
print(np.unique(array3))


[1 2 3]


Problem 3
Write a NumPy program to sort an along the first, last axis of an array.
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]



In [31]:

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
input_array = []
for i in range(rows):
    row_input = input(f"Enter elements for row {i + 1} separated by spaces: ")
    row = list(map(int, row_input.split()))
    input_array.append(row)
x=np.sort(input_array,axis=0)
print(x)
y=np.sort(x,axis=-1)
print(y)

[[2 1]
 [4 6]]
[[1 2]
 [4 6]]


Problem 4
Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
Sample Output:
Original array:
[10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
[4,1,7,3]


In [35]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))
elements,counts=np.unique(array1,return_counts=True)
print(counts)

[4 1 7 3]


Problem 5
Write a NumPy program to remove nan values from a given array.
Sample Output:
Original array:200. 300. nan nan nan 700.
[]
After removing nan values:
[200. 300. 700.]

In [43]:
import pandas as pd
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(float, array1_input.split())))
for i in array1:
    if pd.notnull(i):
        print(i,end=" ")


200.0 300.0 700.0 

In [63]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(float, array1_input.split())))
for i in array1:
    if ~np.isnan(i):
        print(i,end=" ")

200.0 300.0 700.0 

Problem 6
Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
Sample Output:
50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6

In [61]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))
median1=np.percentile(array1,50)
median2=np.percentile(array1,40)
median3=np.percentile(array1,90)
print(median1)
print(median2)
print(median3)


3.0
2.6
4.6


Problem 7
Write a NumPy program to find indices of elements equal to zero in a NumPy array.
Sample Output:
Original array:1 0 2 0 3 0 4 5 6 7 8
[]
Indices of elements equal to zero of the said array:
[1 3 5]

In [70]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))
indices=np.where(array1==0)[0]
print(indices)

[1 3 5]


Problem 8
Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]

In [59]:
import numpy as np
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(float, array1_input.split())))
result = np.round(np.absolute(array1))
print(result)


[1. 2. 2. 0. 2. 2. 2.]


Problem 9
Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]

In [3]:
import numpy as np
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))

list1 = [0, 0]
for i in range(len(array1) - 1):
    diff = array1[i+1] - array1[i ]
    list1.append(diff)

list1.append(200)  
print(list1)



[0, 0, 2, 2, 2, -7, 200]


In [ ]:
import numpy as np
original_array = np.array([1, 3, 5, 7, 0])
print(original_array)
diff_array = np.diff(original_array)
diff_array = np.concatenate(([0, 0], diff_array))
diff_array = np.append(diff_array, [200])
print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append [200] to the array:")
print(diff_array)


Problem 10
Write a NumPy program to get the indices of the sorted elements of a given array.
Expected Output:
Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]

In [71]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))
print(np.argsort(array1))

[0 3 4 6 1 5 2]


Problem 11
Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
Sample output:
Original array:
[ 70 50 20 30 -11 60 50 40]
After partitioning on 4 the position:
[-11 30 20 40 50 50 60 70]

In [4]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split())))
print(np.partition(array1,(0,len(array1)//2)))

[-11  30  20  40  50  50  60  70]


Problem 12
Compute the euclidean distance between two arrays a and b.
Input:
[1,2,3,4,5]
[4,5,6,7,8]
Euclidean distance is: 6.7082


In [51]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split(","))))
array2_input = input("Enter elements for array2 separated by spaces: ")
array2 = np.array(list(map(int, array2_input.split(","))))
print("Euclidean distance is",np.sqrt(np.sum(np.square(array1-array2))))

Euclidean distance is 6.708203932499369


Problem 13
Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Input:
array([1, 3, 7, 1, 2, 6, 0, 1])
Desired Output:
array( [2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.

In [47]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split(","))))
peak=[]
for i in range(len(array1-1)-1):
    if array1[i]>array1[i+1] and array1[i]>array1[i-1]:
        peak.append(i)
result=np.array(peak)
print(result)

[2 5]


Problem 14
Find the index of nth repetition of number i .
Inputs
array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 (from user)
i = 1 (from user)
Output
8

In [45]:
array1_input = input("Enter elements for array1 separated by spaces: ")
array1 = np.array(list(map(int, array1_input.split(","))))
i=int(input("enter the value of i"))
n=int(input("enter the value of n"))
indices=np.where(array1==i)[0]
result=indices[n-1]if n<=len(indices) else -1
print(result)

8
